/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            /**
             * Техническое имя поля. Используется в отправке формы, шаблонах писем и на фронтенде. Лучше не менять после подключения формы на сайт.
             */
            name: string;
            /**
             * Подпись, которую увидит пользователь на сайте.
             */
            label?: string | null;
            /**
             * Ширина поля в сетке формы.
             */
            width?: number | null;
            /**
             * Если включено, поле обязательно для заполнения.
             */
            required?: boolean | null;
            /**
             * Значение, которое будет подставлено по умолчанию.
             */
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            /**
             * Техническое имя поля. Используется в отправке формы, шаблонах писем и на фронтенде. Лучше не менять после подключения формы на сайт.
             */
            name: string;
            /**
             * Подпись, которую увидит пользователь на сайте.
             */
            label?: string | null;
            /**
             * Ширина поля в сетке формы.
             */
            width?: number | null;
            /**
             * Если включено, поле обязательно для заполнения.
             */
            required?: boolean | null;
            /**
             * Подсказка внутри поля на фронтенде.
             */
            placeholder?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            /**
             * Информационный текст, который отображается внутри формы.
             */
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            /**
             * Техническое имя поля. Используется в отправке формы, шаблонах писем и на фронтенде. Лучше не менять после подключения формы на сайт.
             */
            name: string;
            /**
             * Подпись, которую увидит пользователь на сайте.
             */
            label?: string | null;
            /**
             * Ширина поля в сетке формы.
             */
            width?: number | null;
            /**
             * Значение, которое будет подставлено по умолчанию.
             */
            defaultValue?: number | null;
            /**
             * Если включено, поле обязательно для заполнения.
             */
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            /**
             * Техническое имя поля. Используется в отправке формы, шаблонах писем и на фронтенде. Лучше не менять после подключения формы на сайт.
             */
            name: string;
            /**
             * Подпись, которую увидит пользователь на сайте.
             */
            label?: string | null;
            /**
             * Ширина поля в сетке формы.
             */
            width?: number | null;
            /**
             * Значение, которое будет подставлено по умолчанию.
             */
            defaultValue?: string | null;
            /**
             * Подсказка внутри поля на фронтенде.
             */
            placeholder?: string | null;
            /**
             * Варианты выбора для select, radio или checkbox.
             */
            options?:
              | {
                  /**
                   * Подпись, которую увидит пользователь на сайте.
                   */
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Если включено, поле обязательно для заполнения.
             */
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            /**
             * Техническое имя поля. Используется в отправке формы, шаблонах писем и на фронтенде. Лучше не менять после подключения формы на сайт.
             */
            name: string;
            /**
             * Подпись, которую увидит пользователь на сайте.
             */
            label?: string | null;
            /**
             * Ширина поля в сетке формы.
             */
            width?: number | null;
            /**
             * Значение, которое будет подставлено по умолчанию.
             */
            defaultValue?: string | null;
            /**
             * Если включено, поле обязательно для заполнения.
             */
            required?: boolean | null;
            /**
             * Подсказка внутри поля на фронтенде.
             */
            placeholder?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            /**
             * Техническое имя поля. Используется в отправке формы, шаблонах писем и на фронтенде. Лучше не менять после подключения формы на сайт.
             */
            name: string;
            /**
             * Подпись, которую увидит пользователь на сайте.
             */
            label?: string | null;
            /**
             * Ширина поля в сетке формы.
             */
            width?: number | null;
            /**
             * Значение, которое будет подставлено по умолчанию.
             */
            defaultValue?: string | null;
            /**
             * Если включено, поле обязательно для заполнения.
             */
            required?: boolean | null;
            /**
             * Подсказка внутри поля на фронтенде.
             */
            placeholder?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
        | {
            /**
             * Техническое имя поля. Используется в отправке формы, шаблонах писем и на фронтенде. Лучше не менять после подключения формы на сайт.
             */
            name: string;
            /**
             * Подпись, которую увидит пользователь на сайте.
             */
            label?: string | null;
            /**
             * Ширина поля в сетке формы.
             */
            width?: number | null;
            /**
             * Значение, которое будет подставлено по умолчанию.
             */
            defaultValue?: string | null;
            /**
             * Варианты выбора для select, radio или checkbox.
             */
            options?:
              | {
                  /**
                   * Подпись, которую увидит пользователь на сайте.
                   */
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Если включено, поле обязательно для заполнения.
             */
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'radio';
          }
      )[]
    | null;
  /**
   * Текст кнопки отправки формы.
   */
  submitButtonLabel?: string | null;
  /**
   * Что должно произойти после успешной отправки формы.
   */
  confirmationType?: ('message' | 'redirect') | null;
  /**
   * Сообщение, которое увидит пользователь после успешной отправки.
   */
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    /**
     * Ссылка, на которую нужно перенаправить пользователя после отправки.
     */
    url: string;
  };
  /**
   * Уведомления, которые будут отправляться после успешной отправки формы.
   */
  emails?:
    | {
        /**
         * Основной адрес получателя уведомления.
         */
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        /**
         * Адрес, на который будет удобно отвечать из письма.
         */
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Информационный текст, который отображается внутри формы.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Технический ключ для загрузки формы на фронтенде. Например: home-ai-lead
   */
  slug: string;
  formType?: ('section' | 'modal') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  sourcePage?: string | null;
  sourceSection?: string | null;
  modalType?: string | null;
  product?: string | null;
  intent?: string | null;
  utmSource?: string | null;
  utmMedium?: string | null;
  utmCampaign?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              placeholder?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              placeholder?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              placeholder?: T;
              id?: T;
              blockName?: T;
            };
        radio?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  slug?: T;
  formType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  sourcePage?: T;
  sourceSection?: T;
  modalType?: T;
  product?: T;
  intent?: T;
  utmSource?: T;
  utmMedium?: T;
  utmCampaign?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}